services:
  node1:
    # Using Chronosphere LTS image
    image: ghcr.io/calyptia/core/calyptia-fluent-bit:24.11.1
    # OR any image with a shell, e.g.
    # image: fluent/fluent-bit:3.1.10-debug
    ports:
      # HTTP server communication
      - ':8090'
      # Inject alerts via HTTP
      - ':8095'
    volumes:
      - ./fluent-bit-config:/fluent-bit/etc/
    tmpfs: /logs
    # This file is excluded from git
    env_file: .env
    environment:
      FB_CONFIG_DIR: /fluent-bit/etc/
      LOG_DIR: /logs/
      CHAT_OPS_SVR: http-slack-server
      CHAT_OPS_PORT: '8080'
    working_dir: /fluent-bit/etc/

  http-slack-server:
    build:
      # A pre-built image is pushed automatically by the repo
      # image: ghcr.io/fluent/fluent-bit-chatops-demo
      context: .
      dockerfile: Dockerfile
    ports:
      - ':8080'
    env_file: .env
