name: Build slack server container
on:
    workflow_dispatch:
    push:
        branches:
          - main
        paths-ignore:
            - 'scripts/**'
            - 'docs/**'
    pull_request:
        paths-ignore:
            - 'scripts/**'
            - 'docs/**'

jobs:
    build-containers:
        name: Build containers
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata from Github
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: |
                  ghcr.io/${{ github.repository }}
                tags: |
                    type=schedule
                    type=ref,event=branch
                    type=ref,event=pr
                    type=ref,event=tag
                    # set latest tag for default branch
                    type=raw,value=latest,enable={{is_default_branch}}
                    # Add SHA
                    type=sha

            - name: Build the images
              id: container
              uses: docker/build-push-action@v5
              with:
                platforms: ${{ (github.event_name == 'pull_request' && 'linux/amd64') || 'linux/amd64, linux/arm64' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                push: true
